spring.application.name=ordernow-backend
server.port=${PORT:8080}
app.cors.allowed-origins=${FRONTEND_URLS:http://localhost:4200,http://127.0.0.1:4200,http://localhost:5173}

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret.key=${TOKEN_KEY}